version: '3.3'
services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: password-management
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: pass-manag-db
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: password_manager
            MYSQL_USER: latihan
            MYSQL_PASSWORD: latihan
        ports:
            - 6036:3306
